# Generated by Django 2.2.7 on 2019-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Membro da equipe'),
        ),
    ]
